### NumPy Excersises

In [3]:
## importing Numpy
import numpy as np

In [ ]:
## creating a 1D array
arr1 = np.array([1,2,3,4,5])  ## creates an array of n dimension
print(arr1)
print(arr1.shape) ## prints the shape of the array, whether 1D, 2D, 3D

'''
 When the shape of array returns in (), the number(s) inside explains what tyoe of array it is.
 For e.g, as our example, we got (5,). This means a 1D array.
'''

[1 2 3 4 5]
(5,)


In [ ]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

'''
Here, we got (2,5). This means a 2D array with 2 Rows & 5 Colums.
'''

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
## Using in-built method to create array
np.arange(0,10,2)

## Reshaping the created array
shaped_arr = np.arange(0,10,2).reshape(5,1)
print(shaped_arr)   ##This reshapes it to a 2D array with 5 rows and 1 column

[[0]
 [2]
 [4]
 [6]
 [8]]


In [10]:
## creating an array of 1s at a go
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])