### NumPy Excersises

In [3]:
## importing Numpy
import numpy as np

In [ ]:
## creating a 1D array
arr1 = np.array([1,2,3,4,5])  ## creates an array of n dimension
print(arr1)
print(arr1.shape) ## prints the shape of the array, whether 1D, 2D, 3D

'''
 When the shape of array returns in (), the number(s) inside explains what tyoe of array it is.
 For e.g, as our example, we got (5,). This means a 1D array.
'''

[1 2 3 4 5]
(5,)


In [ ]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

'''
Here, we got (2,5). This means a 2D array with 2 Rows & 5 Colums.
'''

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)
